Traceback (most recent call last):
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
lp_series_list = []
syn_series_list = []
m = 13 # Embedding dimension

for idx,series in enumerate(ms.series_list):
    core_series = series.slice((min(initial_series.time),max(initial_series.time)))
    binned_series = initial_series.bin(time_axis=core_series.time).convert_time_unit('Years').detrend(method='savitzky-golay')
    syn_series_list.append(binned_series)
    td = amt.TimeEmbeddedSeries(series=binned_series.interp(),m=m)
    print(f'{series.label} tau is : {td.tau}')
    eps = td.find_epsilon(eps=1,target_density=.05,tolerance=.01)
    rm = eps['Output']
    lp_series = rm.laplacian_eigenmaps(w_size=50,w_incre=5).convert_time_unit('ka')
    lp_series.label = series.label
    lp_series.value_name='FI'
    lp_series.value_unit='NA'
    lp_series_list.append(lp_series)

syn_ms = pyleo.MultipleSeries(syn_series_list)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[8], line 9[0m
[1;32m      7[0m binned_series [38;5;241m=[39m initial_series[38;5;241m.[39mbin(time_axis[38;5;241m=[39mcore_series[38;5;241m.[39mtime)[38;5;241m.[39mconvert_time_unit([38;5;124m'[39m[38;5;124mYears[39m[38;5;124m'[39m)[38;5;241m.[39mdetrend(method[38;5;241m=[39m[38;5;124m'[39m[38;5;124msavitzky-golay[39m[38;5;124m'[39m)
[1;32m      8[0m syn_series_list[38;5;241m.[39mappend(binned_series)
[0;32m----> 9[0m td [38;5;241m=[39m [43mamt[49m[38;5;241;43m.[39;49m[43mTimeEmbeddedSeries[49m[43m([49m[43mseries[49m[38;5;241;43m=[39;49m[43mbinned_series[49m[38;5;241;43m.[39;49m[43minterp[49m[43m([49m[43m)[49m[43m,[49m[43mm[49m[38;5;241;43m=[39;49m[43mm[49m[43m)[49m
[1;32m     10[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mseries[38;5;241m.[39mlabel[38;5;132;01m}[39;00m[38;5;124m tau is : [39m[38;5;132;01m{[39;00mtd[38;5;241m.[39mtau[38;5;132;01m}[39;00m[38;5;124m'[39m)
[1;32m     11[0m eps [38;5;241m=[39m td[38;5;241m.[39mfind_epsilon(eps[38;5;241m=[39m[38;5;241m1[39m,target_density[38;5;241m=[39m[38;5;241m.05[39m,tolerance[38;5;241m=[39m[38;5;241m.01[39m)

File [0;32m~/miniconda3/envs/ammonyte/lib/python3.10/site-packages/ammonyte/core/time_embedded_series.py:77[0m, in [0;36mTimeEmbeddedSeries.__init__[0;34m(self, series, m, tau, embedded_data, embedded_time, value_name, value_unit, time_name, time_unit, label)[0m
[1;32m     73[0m     [38;5;28mself[39m[38;5;241m.[39mtau [38;5;241m=[39m tau_search([38;5;28mself[39m[38;5;241m.[39mseries)
[1;32m     75[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39membedded_data [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m---> 77[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m([38;5;28mself[39m[38;5;241m.[39mseries, (pyleo[38;5;241m.[39mcore[38;5;241m.[39mSeries, [43mpyleo[49m[38;5;241;43m.[39;49m[43mcore[49m[38;5;241;43m.[39;49m[43mLipdSeries[49m)):
[1;32m     78[0m         values [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mseries[38;5;241m.[39mvalue
[1;32m     79[0m         time_axis [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mseries[38;5;241m.[39mtime[:([38;5;241m-[39m[38;5;28mself[39m[38;5;241m.[39mm[38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39mtau)]

[0;31mAttributeError[0m: module 'pyleoclim.core' has no attribute 'LipdSeries'

