Traceback (most recent call last):
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/alexjames/miniconda3/envs/ammonyte/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
end_time=10000

NGRIP_lipd = pyleo.Lipd('../data/8k_ice/NGRIP.NGRIP.2004.lpd')
NGRIP_tso = NGRIP_lipd.to_LipdSeriesList()
NGRIP_series = NGRIP_tso[0].slice((0,end_time))
NGRIP_series.time_unit = 'ka'
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[5], line 3[0m
[1;32m      1[0m end_time[38;5;241m=[39m[38;5;241m10000[39m
[0;32m----> 3[0m NGRIP_lipd [38;5;241m=[39m [43mpyleo[49m[38;5;241;43m.[39;49m[43mLipd[49m([38;5;124m'[39m[38;5;124m../data/8k_ice/NGRIP.NGRIP.2004.lpd[39m[38;5;124m'[39m)
[1;32m      4[0m NGRIP_tso [38;5;241m=[39m NGRIP_lipd[38;5;241m.[39mto_LipdSeriesList()
[1;32m      5[0m NGRIP_series [38;5;241m=[39m NGRIP_tso[[38;5;241m0[39m][38;5;241m.[39mslice(([38;5;241m0[39m,end_time))

[0;31mAttributeError[0m: module 'pyleoclim' has no attribute 'Lipd'

